### ISSUE TITLE
Suggestion: What do I call this

### ISSUE THREAD

**Issue by foursplaysroblox** [DaMoyai/oldcord#4]
![image](https://user-images.githubusercontent.com/82078139/229415939-535a6024-1e08-4629-ae1c-cc84dc3c7c88.png)
![image](https://user-images.githubusercontent.com/82078139/229416351-1a868ccd-4b76-4828-8fa5-6c57bf7b568c.png)

**Comment by DaMoyai** [comment]
i guess channel header, what about it?

**Comment by DaMoyai** [comment]
```css
.emptyChannelIcon-1YdEz2,
.header-1dhDWV,
.container-1yy5xN .wrapper-3Un6-K {
    display: none;
}
.container-1yy5xN {
    min-height: 95px;
    background: url(https://cdn.discordapp.com/attachments/1011371685980684308/1011374467466928208/Chat_Header_1.png),url(https://cdn.discordapp.com/attachments/1011371685980684308/1011374495375818852/Chat_Header_2.png);
    background-position: 0 100%,100% 100%;
    background-repeat: no-repeat,no-repeat;
    background-size: 192px 80px,216px 64px;
    border-bottom: 1px solid hsla(0,0%,100%,.02);
    padding-bottom: 14px;
}
.theme-light .container-1yy5xN {
    background: url(https://cdn.discordapp.com/attachments/1011371707136749682/1011374624333889576/Chat_Header_1.png),url(https://cdn.discordapp.com/attachments/1011371707136749682/1011374646156853358/Chat_Header_2.png);
    background-position: 0 100%,100% 100%;
    background-repeat: no-repeat,no-repeat;
    background-size: 192px 80px,216px 64px;
    border-bottom: 1px solid #eceeef;
}
```
just paste that into custom css or whatever

**Comment by foursplaysroblox** [comment]
thanks but the announcements thing does not work

**Comment by DaMoyai** [comment]
```css
.form-3gdLxP :is(.channelTextArea-1VQBuV, .wrapper-2SplAX) {
  margin-bottom: 30px;
}
.form-3gdLxP .wrapper-2SplAX {
  border-radius: 0;
  background: #0000;
  background-position: 0 100%, 100% 100%;
  background-repeat: no-repeat, no-repeat;
  background-size: 187px 39px;
  justify-content: center;
  flex-direction: column;
  gap: 8px;
  margin-top: -8px;
}
.theme-dark .form-3gdLxP .wrapper-2SplAX {
  background-image: url(https://cdn.discordapp.com/attachments/733624227378495488/1009438687521677405/unknown.png), url(https://cdn.discordapp.com/attachments/733624227378495488/1009438687827873812/unknown.png);
}
.theme-light .form-3gdLxP .wrapper-2SplAX {
  background-image: url(https://cdn.discordapp.com/attachments/733624227378495488/1009438799039844454/unknown.png), url(https://cdn.discordapp.com/attachments/733624227378495488/1009438799429898251/unknown.png);
}
.form-3gdLxP .wrapper-2SplAX .image-3FliiM {
  display: none;
}
.form-3gdLxP .wrapper-2SplAX .title-Do_30w {
  font-size: 14px;
  font-weight: 500;
}
.theme-dark .form-3gdLxP .wrapper-2SplAX .title-Do_30w {
  color: #ffffff;
}
.form-3gdLxP .wrapper-2SplAX .content-2M_BlY {
  height: auto;
  margin: 0;
}
.form-3gdLxP .wrapper-2SplAX .buttonContainer-KMz3Ex {
  margin: 0;
  gap: 8px;
}
.form-3gdLxP .wrapper-2SplAX .text-2GfGMu {
  text-align: center;
}
.form-3gdLxP .wrapper-2SplAX .lookFilled-1H2Jvj.colorPrimary-2-Lusz {
  margin: 0;
  padding: 0;
  min-width: 0;
  min-height: 0;
  height: auto;
  font-size: 12px;
  text-transform: uppercase;
  font-weight: 700;
  background: none !important;
  color: var(--blurple);
}
.form-3gdLxP .wrapper-2SplAX .lookFilled-1H2Jvj.colorPrimary-2-Lusz .contents-3NembX {
  color: var(--blurple);
}
.form-3gdLxP .wrapper-2SplAX .lookFilled-1H2Jvj.colorPrimary-2-Lusz:hover {
  text-decoration: underline;
}
```
![image](https://user-images.githubusercontent.com/51537072/230573916-7159276a-51d1-4be0-a782-6bc0b2e31054.png)
