### ISSUE TITLE
Requesting a CSS Code

### ISSUE THREAD

**Issue by foursplaysroblox** [damoyai/oldcord#7]
Do you have a css code for the rounded role thing
![image](https://user-images.githubusercontent.com/82078139/230698085-d0201db4-a389-4d4f-9cf7-1a0be7f61753.png)

**Comment by DaMoyai** [comment]
```css

.root-jbEB5E {
	position: relative;
	margin-top: 2px;
}
.role-2TIOKu {
	background-color: transparent;
}

.addButtonIcon-3HZ_2f {
	width: 10px;
	height: 10px;
}

.theme-dark .actionButton-1YKTU0 {
	border-color: var(--background-accent);
	color: #b9bbbe;
	background: 0 0;
}

.role-2TIOKu {
	transform: translate(0);
	border: 0;
	border-radius: 4200px;
}
.role-2TIOKu .roleRemoveIcon-387wKV {
	margin: 0;
	left: unset;
	transform: translate(50%, -50%);
}
.role-2TIOKu .roleRemoveButton-17oXnT {
	position: static;
}
/* Add a colored border around the role */
.role-2TIOKu .roleRemoveButton-17oXnT .roleCircle-3TFUOr:before {
	content: "";
	top: 0;
	left: 0;
	z-index: -1;
	width: 100%;
	height: 100%;
	box-sizing: border-box;
	position: absolute;
	background: inherit;
	border-radius: 420px;
	border: 0.65px solid transparent;
	-webkit-mask: linear-gradient(#000 0 0) padding-box, linear-gradient(#000 0 0);
	-webkit-mask-composite: xor;
}
/* border around addrole button*/
.addButton-1_dZYu {
	border: 1px solid;
}
```
